blog/urls.py
from django.urls import path

from blog.feeds import LatestPostsFeed
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    path('feed/',  LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

django_blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.generic import RedirectView

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/blog/', permanent=False), name='index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models import Manager
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=256, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # manager
    objects = Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    # parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='sub_comments', null=True, blank=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=32)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
import datetime

from django.conf import settings
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
# Create your views here.
from django.views.generic import ListView
from taggit.models import Tag

from blog import pager
from blog.forms import EmailPostForm, CommentForm, SearchForm
from blog.models import Post


def log(c):
    print(datetime.datetime.now(), c)


def post_list(request, tag_slug=None):
    all_posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        all_posts = all_posts.filter(tags__in=[tag])
        # todo delete
        # log(all_posts.query)
    paginator = Paginator(all_posts, settings.POSTS_PER_PAGE)
    page = request.GET.get('page', 1)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    page_obj = pager.Page(posts.number, paginator.num_pages)
    return render(request, 'blog/post/list.html', {
        'posts': posts,
        'page': page,
        'tag': tag,
        'page_obj': page_obj,
    })


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day)

    comment_form = CommentForm(request.POST or None)
    comments = post.comments.filter(active=True)
    new_comment = None
    # post method and valid
    if comment_form.is_valid():
        new_comment = comment_form.save(commit=False)
        new_comment.post = post
        new_comment.save()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    # todo delete
    # log(similar_posts.query)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
        '-same_tags', '-publish')[:4]
    # todo delete
    # log(similar_posts.query)
    log(similar_posts.all())
    return render(
        request, 'blog/post/detail.html', {
            'post': post,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'similar_posts': similar_posts,
        })


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'],
                                                                   post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url,
                                                                     cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm(request.GET or None)
    query = None
    posts = None
    page_obj = None
    paginator = None
    if form.is_valid():
        query = form.cleaned_data['query']

        search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
        search_query = SearchQuery(query)
        posts = Post.published.annotate(rank=SearchRank(search_vector, search_query)).filter(
            rank__gte=0.3).order_by('-rank')
        paginator = Paginator(posts, settings.POSTS_PER_PAGE)
        page = request.GET.get('page', 1)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        page_obj = pager.Page(posts.number, paginator.num_pages)

    return render(request, 'blog/post/list.html', {
        'query': query,
        'paginator': paginator,
        'posts': posts,
        'page_obj': page_obj,
    })

blog/templates/blog/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark light-blue darken-3" style="background-color: #1a75d2 !important;">
    <div class="container">
        <a class="navbar-brand" href="/">学思</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {#                <li class="nav-item active">#}
                {#                    <a class="nav-link" href="#">主页#}
                {#                        <span class="sr-only">(current)</span>#}
                {#                    </a>#}
                {#                </li>#}
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link" href="#">Features</a>#}
                {#                </li>#}
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link" href="#">Pricing</a>#}
                {#                </li>#}
                {#                <li class="nav-item btn-group">#}
                {#                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"#}
                {#                       aria-haspopup="true" aria-expanded="false">Dropdown#}
                {#                    </a>#}
                {#                    <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">#}
                {#                        <a class="dropdown-item" href="#">Action</a>#}
                {#                        <a class="dropdown-item" href="#">Another action</a>#}
                {#                        <a class="dropdown-item" href="#">Something else here</a>#}
                {#                    </div>#}
                {#                </li>#}
            </ul>
            <form action="{% url "blog:post_search" %}" class="form-inline">
                <input class="form-control mr-sm-2" type="text" placeholder="搜索" name="query" aria-label="Search">
            </form>
        </div>
    </div>
</nav>

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">

    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.css" %}" rel="stylesheet">
    <link href="{% static "css/highlights/default.css" %}" rel="stylesheet">
    <!-- Template styles -->
    <style rel="stylesheet">
        /* TEMPLATE STYLES */

        main {
            padding-top: 2rem;
            padding-bottom: 2rem;
        }

        .widget-wrapper {
            padding-bottom: 2rem;
            border-bottom: 1px solid #e0e0e0;
            margin-bottom: 2rem;
        }

        .navbar {
            background-color: #53463d;
        }

        footer.page-footer {
            background-color: #53463d;
            margin-top: 2rem;
        }

        .list-group-item.active {
            background-color: #a3b0c2;
            border-color: #a3b0c2
        }

        .list-group-item:not(.active) {
            color: #222;
        }

        .list-group-item:not(.active):hover {
            color: #666;
        }

        .card {
            font-weight: 300;
        }

        .navbar .btn-group .dropdown-menu a:hover {
            color: #000 !important;
        }

        .navbar .btn-group .dropdown-menu a:active {
            color: #fff !important;
        }

        .navbar {
            background: #1a75d2 !important;
        }
    </style>

</head>
<body>
<header>
    {% include 'blog/_nav.html' %}
</header>

<main>
    <!--Main layout-->
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-lg-4">
                {#                <div id="sidebar">#}
                <div class="paper-effect-sidebar">
                    <h2>劝学</h2>
                    <p>骐骥一跃，不能十步；驽马十驾，功在不舍。锲而舍之，朽木不折；锲而不舍，金石可镂。蚓无爪牙之利，筋骨之强，上食埃土，下饮黄泉，用心一也。蟹六跪而二螯，非蛇鳝之穴无可寄托者，用心躁也。</p>
                    <hr>
                    <p>已经发布了{% total_posts %}篇博客.</p>
                    <p><a href="{% url "blog:post_feed" %}">RSS订阅我的博客</a></p>
                    <section class="wow fadeIn" data-wow-delay="0.4s">
                        <h4 class="font-bold dark-grey-text">最近发布</h4>
                        {% show_latest_posts 5 %}
                    </section>
                    <section class="wow fadeIn" data-wow-delay="0.4s">
                        <h4 class="font-bold dark-grey-text mb-3">评论最多</h4>
                        {% get_most_commented_posts as most_commented_posts %}
                        <ul>
                            {% for post in most_commented_posts %}
                                <li>
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </section>
                    {#                </div>#}
                    <section class="wow fadeIn" data-wow-delay="0.4s">
                        <h4 class="font-bold dark-grey-text mb-3">归档</h4>
                        <!--List-->
                        <ul class="list mt-3">
                            {% for archive in archives %}
                                <li>
                                    <h6 class="">
                                        <a href="#!" class="grey-text">{{ archive.year }}年{{ archive.month }}月</a>
                                    </h6>
                                </li>
                                {#                        {% empty %}#}
                                {#                            No archives yet#}
                            {% endfor %}
                        </ul>
                    </section>

                </div>

            </div>
        </div>
</main>
<small class="container">
    <footer class="bd-footer text-muted">
        <hr>
        <div class="container-fluid p-3 p-md-5">
            <p style="text-align: center; margin-bottom: 0px;">Design &amp; Built with ♥ by <b>Vincent Wei</b></p>
            <p style="text-align: center">&copy; 2018 | <b>Vincent Wei</b> All rights reserved</p>
        </div>
    </footer>
</small>
</body>
</html>

blog/templates/blog/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container">
        <a class="navbar-brand" href="#">代码匠</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ 1 }}">博客<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">关于我</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0 input-group-sm">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-primary my-2 my-sm-0 btn-sm" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="paper-effect">
        <h1 class="text-center h1-responsive font-bold dark-grey-text">{{ post.title }}</h1>
        <p class="date text-center">
            发布于 {{ post.publish }}
        </p>
        <div class="markdown-body">
            {{ post.body|markdown }}
        </div>
        {#        <p>#}
        {#            <a href="{% url "blog:post_share" post.id %}">#}
        {#                Share this post#}
        {#            </a>#}
        {#        </p>#}
    </div>
    {% if similar_posts %}
        <div class="paper-effect mt-3">
            <h3 class="h3-responsive dark-grey-text">相似文章</h2>
                <ul>
                    {% for similar_post in similar_posts %}
                        <li>
                            <a href="{{ similar_post.get_absolute_url }}">{{ similar_post.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
        </div>
    {% endif %}

    {% if comments %}
        <div class="paper-effect mt-3">
            {% with comments.count as total_comments %}
                <h2>
                    {{ total_comments }}条评论
                </h2>
            {% endwith %}
            {% for comment in comments %}
                <div class="comment">
                    <p class="info">
                        评论 {{ forloop.counter }} by {{ comment.name }}
                        {{ comment.created }}
                    </p>
                    {{ comment.body|linebreaks }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="container mt-3">
        {% if new_comment %}
            <h2>评论添加成功！</h2>
        {% else %}
            <h2>添加评论</h2>
            <form action="." method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" class="mt-4 btn btn-blue btn-md" value="添加评论"></p>
            </form>
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}我的博客{% endblock %}

{% block content %}
    {#    <h1 class="mb-4">博客</h1>#}
    {% if tag %}
        <h2>标签为"{{ tag.name }}"的文章如下</h2>
    {% endif %}
    {#    {% for post in posts %}#}
    {#        <h2>#}
    {#            <a href="{{ post.get_absolute_url }}">#}
    {#                {{ post.title }}#}
    {#            </a>#}
    {#        </h2>#}
    {#        <p class="tags">Tags:#}
    {#            {% for tag in post.tags.all %}#}
    {#                <a href="{% url "blog:post_list_by_tag" tag.slug %}">#}
    {#                    {{ tag.name }}#}
    {#                </a>#}
    {#                {% if not forloop.last %}, {% endif %}#}
    {#            {% endfor %}#}
    {#        </p>#}
    {#        <p class="date">#}
    {#            Published {{ post.publish }} by {{ post.author }}#}
    {#        </p>#}
    {#        {{ post.body|markdown|truncatewords:30 }}#}
    {#    {% endfor %}#}
    {% if query %}

        <h1>"{{ query }}"的搜索结果如下</h1>
        <h3>
            {% with paginator.count as total_results %}
                找到{{ total_results }}个结果
            {% endwith %}
        </h3>
    {% endif %}

    {% if posts %}

        {% for post in posts %}


            <div {% if not forloop.first %} class="paper-effect mt-4" {% else %} class="paper-effect" {% endif %}>
                <!--Post-->
                <div class="post-wrapper wow fadeIn" data-wow-delay="0.2s">
                    <!--Post data-->
                    <h2 style="text-align: center" class="h2-responsive dark-grey-text font-bold"><a
                            class="dark-grey-text"
                            href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        <small class="text-muted"></small>
                    </h2>
                    <p style="text-align: center;" class="tags small text-muted">
                        {% for tag in post.tags.all %}
                            <a href="{% url "blog:post_list_by_tag" tag.slug %}" class="fa fa-tag">
                                {{ tag.name }}
                            </a>
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                        - <span style="text-align: center;">{{ post.publish }}</span>
                    </p>

                    <br>

                    <!--Featured image -->
                    {#            <div class="view overlay hm-white-light z-depth-1-half rounded">#}
                    {#                <img src="https://mdbootstrap.com/img/Photos/Others/images/76.jpg" class="img-fluid" alt="">#}
                    {#                <div class="mask">#}
                    {#                </div>#}
                    {#            </div>#}

                    <br>

                    <!--Post excerpt-->
                    <p>{{ post.body|markdown|striptags|truncatewords:30 }}</p>

                    <!--"Read more" button-->
                    <a href="{{ post.get_absolute_url }}" class="btn btn-blue btn-md">阅读全文</a>
                </div>
                <!--/.Post-->
            </div>
            {#        {% if not forloop.last %}#}
            {#            <hr class="mb-5">#}
            {#        {% endif %}#}
        {% endfor %}
        {% include "pagination.html" with page=page_obj %}
    {% endif %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% block title %}Search{% endblock %}

{% block content %}
    <div class="paper-effect">

        {% if query %}
            <h1>Posts containing "{{ query }}"</h1>
            <h3>
                {% with results.count as total_results %}
                    Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
            </h3>
            {% for post in results %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|truncatewords:5 }}
            {% empty %}
                <p>There are no results for your query.</p>
            {% endfor %}
            <p><a href="{% url "blog:post_search" %}">Search again</a></p>
        {% else %}
            <h1>Search for posts</h1>
            <form action="." method="get">
                {{ form.as_p }}
                <input type="submit" value="Search">
            </form>
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent == True %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<!--/.Pagination-->
{% load blog_tags %}
<nav class="mt-5">
    <ul class="pagination flex-center pg-primary  wow fadeIn" data-wow-delay="0.2s">
        {% if page.has_left %}
            <li class="page-item">
                <a class="page-link" href="?{% query_transform page=page.number|add:-1 %}">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">上一页</span>
                </a>
            </li>
        {% endif %}
        {% if page.has_left_most %}
            <li class="page-item"><a class="page-link" href="?{% query_transform page=1 %}">1</a></li>
            {% if page.has_left_most_ellipsis %}
                <li><span>...</span></li>
            {% endif %}
        {% endif %}
        {% for i in page.page_range %}
            <li {% ifequal page.number i %}class="page-item active" {% else %} class="page-item" {% endifequal %}>
                <a href="?{% query_transform page=i %}" class="page-link">{{ i }}</a>
            </li>
        {% endfor %}

        {% if page.has_right_most %}
            {% if page.has_right_most_ellipsis %}
                <li><span>...</span></li>
            {% endif %}
            <li class="page-item"><a class="page-link"
                                     href="?{% query_transform page=page.num_pages %}">{{ page.num_pages }}</a></li>
        {% endif %}
        {% if page.has_right %}
            <li class="page-item">
                <a class="page-link" href="?{% query_transform page=page.number|add:1 %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">下一页</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>